service: microservice-reference

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: eu-west-2

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: get
    tags:
      endpoint: "hello"
      module: "hello"
    package:
      include:
        - hello.js
